#!/bin/bash

set -e -o pipefail

log "Generating virtual user ..."
# TODO: Do setup ...

log "Starting supervisord ..."
/usr/bin/supervisord --configuration=/etc/supervisor/supervisord.conf &
sleep 1
while [[ $(pgrep --count --full /usr/lib/postfix/sbin/master) -eq 0 ]] ; do
	log "Waiting for postfix ..."
	sleep 1
done

log "Testing Mail ..."
test-mail

log "Testing SMTP ..."
postfix-test-smtp "${user_name}" "${user_password}" "${user_mailbox}"

log "--- Test Passed ---"
exit 0
